export const ROUTES = {
	root: 'root',
	splashScreen: 'splashScreen',
	bottomTabs: 'Home',
	bottombar: 'bottom bar',
	screenHome: 'Home Screen',
	drawer: 'drawer',
	screenSearch: 'Search',
	screenMore: 'More',
	moreStack: 'More Stack',
	screenFavourite: 'Favourites',
	favStack: 'Favourite Stack',
	screenForex: 'Forex',
	screenStock: 'Stock',
	screenCommodities: 'Commodities',
	screenIndices: 'Indices',
	screenCrypto: 'Crypto Currency',
	screenHelp: 'Help',
	screenPrivacy: 'Privacy Policy',
	screenDetails: 'Details',
	screenChart: 'Charts',
	screenCalender: 'Calender',

};
